POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "Jane@reacher.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "e80b5d39-858a-4356-8d16-9407cec05c90"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_to": "d8805595-6213-4f20-bc1b-b7f49abd3c50",
    "account_id_from": "f657a60e-584f-4089-bd8d-32020e68a2d2",
    "amount": 10
}