POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jack Doe",
    "email": "Jack@reacher.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "c92d37d9-ff6f-421a-a206-b747559972f6"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "1617b640-6efd-4a22-bbea-41a02d2b150f",
    "account_id_to": "355edb79-14d6-47e1-b496-20165c0cdd29",
    "amount": 10
}